version: "3.5"
services:
  db:
    container_name: alumind-db
    image: ankane/pgvector
    environment:
      POSTGRES_DB: alumind_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: unless-stopped
  api:
    container_name: alumind
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://alumind-db:5432/alumind_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - 8181:8080
