name: Build
run-name: ${{ github.actor }} building...
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Code Quality Check
        run: mvn checkstyle:check
        continue-on-error: true
      - name: Build the project
        run: mvn clean install
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar

